### PR TITLE
Modified badges for validation

### PR DESCRIPTION
**Pull request by FrenchBen**
Complicated URLs on badges failed validation. 
Signed-off-by: French Ben frenchben@docker.com

### CODE REVIEW

**Comment by FrenchBen** [comment]
PTAL @stevvooe

**Comment by stevvooe** [comment]
I can't say that i understand this regex.

LGTM

**Comment by FrenchBen** [comment]
Due to the case matching and regex rules in go there's some extra escaping rules.

For historical purpose (also made me realize a light tweak was needed):
`(?i)(\[!\[[a-zA-Z0-9_ .]*\]\([0-9a-z.\/:&?=-]*\)\]\([0-9a-z.\/:-?&]*\)?)`
`(?i)` - case incensitive
`( ... )` - First and last parenthesis are to capture matching
`\[!\[[a-zA-Z0-9_ .]*\]` - Match something that looks like a title `[![badge badge]`
`\([0-9a-z.\/:&?=-]*\)\]` - Match something that looks like a url `(some-image-url)]`
`\([0-9a-z.\/:-?&]*\)` - Match something that looks like a url `(some-report-url)
The 3 above match up to the mardown for an image that is a link: 

```
[![badge badge](some-image-url)](some-report-url)
```

`?` - Make the url bit conditional, although the rule isn't perfect here and should be tweaked

You can see the matching pattern here:
http://rubular.com/r/JEs1HLMEFL

**Comment by stevvooe** [comment]
@FrenchBen use the backtic to stay sane here.

**Pull request merged**
